name: S3 deploy with cloud front
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - uses: actions/checkout@v2.6.0

      - name: Install dependencies
        run: yarn

      - name: Build
        run: CI=false yarn build

      - name: Deploy
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3:${{ secrets.S3_BUCKET }}

